// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uRL
 * @param {string} param
 * @returns {Promise.<string>}
 */
export async function ExtractUrlSearchParameter(uRL, param) {
	// BEGIN USER CODE
	const url = new URL(uRL);
	const params = new URLSearchParams(url.search);
	return params.get(param);
	// END USER CODE
}
